

appName: myhelmapp-nghiepnc3

port: 80

namespace: default

configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: 'This app was deployed with helm NGhiepnc!'

image:
  name: devopsjourney1/mywebapp
  tag: latest